INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Hardware', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home and Kitchen', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Beauty and Personal Care', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sports and Outdoors', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Food and Beverages', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Health and Wellness', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tools and Home Improvement', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Movies and TV Shows', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Video Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Art and Crafts', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Travel and Luggage', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Books and Magazines', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home Decor', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Outdoor and Garden', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Party Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Craft Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Business and Industrial', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Collectibles', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Antiques', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Coins and Paper Money', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers and Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Digital Cameras', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Smartphones and Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tablets and Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('TV and Video', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Audio and Home Theater', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Car Audio and Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cameras and Camcorders', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Portable Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Printers and Ink', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Networking and Wi-Fi', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Components', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Gaming Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Virtual Reality Headsets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Monitors and Displays', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Keyboards and Mice', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Storage and Memory', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Software', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Printers and Scanners', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Servers and Workstations', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Cables and Adapters', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Cases and Towers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Power Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Cooling Systems', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Speakers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Microphones', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Headsets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Webcams', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Mounts and Stands', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Desk and Chairs', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Cleaning Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Repair Tools', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Gaming Chairs', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Gaming Desks', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Gaming Monitors', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Gaming Keyboards', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Gaming Mice', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Gaming Headsets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computer Gaming Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Womens Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Mens Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Kids Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Baby Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jackets and Coats', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jeans', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('T-Shirts', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sweaters and Cardigans', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Hoodies and Sweatshirts', NOW());